 # Site settings
title: Strict Mode
email: kurtiskemple@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kkemple.github.io" # the base hostname & protocol for your site
twitter_username: kurtiskemple
github_username:  kkemple
author_name: Kurtis Kemple

# Build settings
markdown: kramdown
keep_files: ['.git']
permalink: /:title